default:
	echo =========== 1
	R CMD install dataPackages/SubjectHistory && R -f dataPackages/SubjectHistory/inst/unitTests/test_SubjectHistory.R 
	echo =========== 2
	R CMD install dataPackages/Dataset && R -f dataPackages/Dataset/inst/unitTests/test_Dataset.R 
	echo =========== 3
	R CMD install dataPackages/DEMOdz && R -f dataPackages/DEMOdz/inst/unitTests/test_DEMOdz.R 
	echo =========== 4
	R CMD install Oncoscape && (cd Oncoscape/inst/unitTests; R -f test_ChinookServer.R)
	echo =========== 5
	R CMD install analysisPackages/ChinookAnalysis && R -f analysisPackages/ChinookAnalysis/inst/unitTests/test_ChinookAnalysis.R
	echo =========== 6
	R CMD install analysisPackages/chinookAnalysisDemo/SimpleSummaryStats && R -f analysisPackages/chinookAnalysisDemo/SimpleSummaryStats/inst/unitTests/test_SimpleSummaryStats.R 
	echo =========== 7
	R CMD install analysisPackages/chinookAnalysisDemo/ChinookSimpleSummaryStats && R -f analysisPackages/chinookAnalysisDemo/ChinookSimpleSummaryStats/inst/unitTests/test_ChinookSimpleSummaryStats.R
	echo =========== 8
	(cd analysisPackages/chinookAnalysisDemo/ChinookSimpleSummaryStats/inst/unitTests; make)
	echo =========== 9
	(cd analysisPackages/chinookAnalysisDemo/ChinookSimpleSummaryStats/inst/unitTests; make)
	echo =========== 10
	R CMD install dataPackages/ChinookDataset  && R -f dataPackages/ChinookDataset/inst/unitTests/test_ChinookDataset.R
	echo =========== 11
	(cd dataPackages/ChinookDataset/inst/unitTests; make)
