git add  Oncoscape/inst/scripts/markersAndSamples/Module.js
git add     Oncoscape/inst/scripts/markersAndSamples/Test.js
git add     Oncoscape/inst/scripts/markersAndSamples/index.html
git add     Oncoscape/inst/scripts/markersAndSamples/makefile
git add     Oncoscape/inst/scripts/markersAndSamples/widgetExperiments.html
git add     dataPackages/DEMOdz/DESCRIPTION
git add     dataPackages/DEMOdz/inst/extdata/ericsEightGliomaClusters.RData
git add     dataPackages/DEMOdz/inst/extdata/verhaakGbmClustersAugmented.RData
git add     dataPackages/TCGAbrain/DESCRIPTION
git add     dataPackages/TCGAbrain/inst/extdata/ericsEightGliomaClusters.RData
git add     dataPackages/TCGAbrain/inst/extdata/manifest.tsv
git add     dataPackages/TCGAgbm/DESCRIPTION
git add     dataPackages/TCGAgbm/inst/extdata/manifest.tsv
