library(NetworkMaker)
library(SttrDataPackage)
library(TCGAbrain)
options(stringsAsFactors=FALSE)
#----------------------------------------------------------------------------------------------------
dz <- TCGAbrain() 
netMaker <- NetworkMaker(dz)
load(system.file(package="NetworkMaker", "extdata", "genesets.RData"))
goi <- sort(unique(genesets$tcga.GBM.classifiers, genesets$marker.genes.545))
gistic.scores <-c(-2, 2)
calculateSampleSimilarityMatrix(netMaker, genes=goi, copyNumberValues=gistic.scores)
g <- getSamplesGraph(netMaker)
rcy <- RCyjs(portRange=6047:6100, quiet=TRUE, graph=g, hideEdges=TRUE)
httpSetStyle(rcy, "style.js")
tbl.pos <- getSampleScreenCoordinates(netMaker, xOrigin=0, yOrigin=0, xMax=2000, yMax=5000)
setPosition(rcy, tbl.pos)    
fit(rcy, 100)
g.chrom <- getChromosomeGraph(netMaker, goi)
httpAddGraph(rcy, g.chrom)
httpSetStyle(rcy, "style.js")
tbl.pos <- getChromosomeScreenCoordinates(netMaker, xOrigin=1400, yOrigin=000, yMax=2000, chromDelta=200)
setPosition(rcy, tbl.pos)
fit(rcy, 100)
g.mut <- getMutationGraph(netMaker, goi)
httpAddGraph(rcy, g.mut)
g.cn <- getCopyNumberGraph(netMaker, goi, gistic.scores)
httpAddGraph(rcy, g.cn)
hideAllEdges(rcy)
showEdges(rcy, "chromosome")
fit(rcy)
g.markers.json <- getJSON(rcy)
filename <- "../extdata/markers.json.TCGAbrain.RData"
printf("saving as %s, %d nodes, %d edges", filename, getNodeCount(rcy), getEdgeCount(rcy))
save(g.markers.json, file=filename)
 
