language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - 'iojs'
before_install:
  - sudo apt-get install r-base
  - sudo apt-get install r-cran-rcpp
  - wget http://cran.r-project.org/src/contrib/Archive/RInside/RInside_0.2.10.tar.gz
  - sudo R CMD INSTALL RInside_0.2.10.tar.gz
  - wget http://cran.r-project.org/src/contrib/RJSONIO_1.3-0.tar.gz
  - sudo R CMD INSTALL RJSONIO_1.3-0.tar.gz
after_script:
  - npm run coveralls
