library(NetworkMaker)
library(SttrDataPackage)
library(DEMOdz)
options(stringsAsFactors=FALSE)
#----------------------------------------------------------------------------------------------------
dz <- DEMOdz() 
netMaker <- NetworkMaker(dz)
gistic.scores <-c(-2, -1, 1, 2)
calculateSampleSimilarityMatrix(netMaker, copyNumberValues=gistic.scores)
g <- getSamplesGraph(netMaker)
rcy <- RCyjs(portRange=6047:6100, quiet=TRUE, graph=g, hideEdges=TRUE)
httpSetStyle(rcy, "style.js")
tbl.pos <- getSampleScreenCoordinates(netMaker, xOrigin=0, yOrigin=0, xMax=2000, yMax=5000)
setPosition(rcy, tbl.pos)    
fit(rcy, 100)
goi <- colnames(matrices(dz)$mtx.mut)
g.chrom <- getChromosomeGraph(netMaker, goi)
httpAddGraph(rcy, g.chrom)
httpSetStyle(rcy, "style.js")
tbl.pos <- getChromosomeScreenCoordinates(netMaker, xOrigin=1400, yOrigin=000, yMax=2000, chromDelta=200)
setPosition(rcy, tbl.pos)
fit(rcy, 100)
g.mut <- getMutationGraph(netMaker, goi)
httpAddGraph(rcy, g.mut)
g.cn <- getCopyNumberGraph(netMaker, goi, gistic.scores)
httpAddGraph(rcy, g.cn)
hideAllEdges(rcy)
showEdges(rcy, "chromosome")
fit(rcy)
g.markers.json <- getJSON(rcy)
filename <- "../extdata/markers.json.DEMOdz.RData"
printf("saving as %s, %d nodes, %d edges", filename, getNodeCount(rcy), getEdgeCount(rcy))
save(g.markers.json, file=filename)
 
