#!/bin/bash
set -e
set -x

ONCOSCAPE_ROOT=$(cd "$(dirname $0)/.." && pwd)
mkdir -p ${ONCOSCAPE_ROOT}/rlibs ${ONCOSCAPE_ROOT}/userdata
export R_LIBS="${ONCOSCAPE_ROOT}/rlibs"

cd $ONCOSCAPE_ROOT && make installLocal
