\documentclass{article}
%% %\VignetteIndexEntry{AnalysisDemo Overview}
%% %\VignettePackage{AnalysisDemo}
\usepackage[noae]{Sweave}
\usepackage[left=0.5in,top=0.5in,right=0.5in,bottom=0.75in,nohead,nofoot]{geometry} 
\usepackage{hyperref}
\usepackage[noae]{Sweave}
\usepackage{color}
\usepackage{graphicx}
\usepackage{caption}
\usepackage{subcaption}

\definecolor{Blue}{rgb}{0,0,0.5}
\definecolor{Green}{rgb}{0,0.5,0}

\RecustomVerbatimEnvironment{Sinput}{Verbatim}{%
  xleftmargin=1em,%
  fontsize=\small,%
  fontshape=sl,%
  formatcom=\color{Blue}%
  }
\RecustomVerbatimEnvironment{Soutput}{Verbatim}{%
  xleftmargin=0em,%
  fontsize=\scriptsize,%
  formatcom=\color{Blue}%
  }
\RecustomVerbatimEnvironment{Scode}{Verbatim}{xleftmargin=2em}



\renewenvironment{Schunk}{\vspace{\topsep}}{\vspace{\topsep}}
\fvset{listparameters={\setlength{\topsep}{6pt}}}
% These determine the rules used to place floating objects like figures 
% They are only guides, but read the manual to see the effect of each.
\renewcommand{\topfraction}{.99}
\renewcommand{\bottomfraction}{.99}
\renewcommand{\textfraction}{0.0}

\title{AnalysisDemo} 
\author{Paul Shannon}

\begin{document} 

\maketitle

\section{Introduction}

We wish to encourage computational biology and biostatistical contributions to Oncoscape.  The general
scheme is

\begin{itemize}
    \item Modify the present package ``AnalysisDemo'' to embody your algorithm
    \item Use unit tests to ensure the code works with a variety of inputs.
    \item Send us your package, and we will wrap it up so that it appears as a computational service within Oncoscape.
    \item Or host it yourself, letting us help as needed to get the websockets/JSON communication working.
\end{itemize}

\section{Run AnalysisDemo in its Distributed Form}

First, install the package.  If you are working in a shell from the command line:

\begin{verbatim}
  R CMD INSTALL AnalysisDemo_0.99.0.tar.gz
\end{verbatim}

You will want to explore the source code, so unpack the tarball, creating an \textbf{AnalysisDemo} directory:
\begin{verbatim}
  tar zxf AnalysisDemo_0.99.0.tar.gz
\end{verbatim}

Now change directories to unitTests, and run those tests:
\begin{verbatim}
  cd AnalysisDemo/inst/unitTests
  ls -l testPackage.R
\end{verbatim}

Start R, ``source'' that file, then run the tests it includes:

\begin{verbatim}
  R> source("testPackage.R")
  R> runTests()  # this is a convenience function which runs five tests (see below)
\end{verbatim}

You will see this output in your R console:


\begin{verbatim}
[1] --- test_noArgs_constructor
[1] --- test_args_constructor
[1] --- test_setExpression
[1] --- test_.trimMatrix
found 5/10 overlapping samples in the expession data, 8/11 overlapping genes
[1] --- test_score
found 8/10 overlapping samples in the expession data, 8/11 overlapping genes
found 8/10 overlapping samples in the expession data, 6/9 overlapping genes
[1] TRUE
\end{verbatim}

\section{Package Architecture and Design}

This package defines a single S4 class, \textbf{AnalysisDemo} defined in AnalysisDemo/R/AnalysisDemo-class.R.
If you are new to R's S4 classes, they will seem a bit odd at first, inspired as they are by the Common Lisp
Object System (CLOS).  We hope that the working example provided here gets you past most of the confusion.

Sample data is provided in two files found within the AnalysisDemo/data directory:

\begin{itemize}
    \item \textbf{tbl.mrnaUnified.TCGA.GBM.RData}: public gene expression data for 325 patients and 12k genes
    \item  \textbf{msigdb.RData}:  genesets from the Broad Institute, lists of gene symbols associated with
published analyses, Gene Ontology terms, KEGG pathways, etc.
\end{itemize}

Unit tests are provided with in a single file, as demonstrated above.  These are extremely useful in at least these two
ways:

\begin{itemize}
    \item They make software engineering robust, and much simpler! \\ See \url{http://www.bioconductor.org/developers/how-to/unitTesting-guidelines}
    \item For the programmer who wishes to use or modify the code, they effectively and compactly document, explain and demonstrate what the code does.
\end{itemize}

\section{What the Unit Tests Do}

\begin{itemize}
    \item \textbf{test\_noArgs\_constructor}:  establishes that the package infrastructure is sound, by creating an empty (and thus not otherwise useful) AnalysisDemo object.
    \item \textbf{test\_args\_constructor}:  makes sure both data items (the expression array, and the msigdb genesets) can be read, that they can be used to create an
AnalysisDemo object, and that accessors (getSampleIDs, getGeneSet) work as expected.
    \item \textbf{test\_setExpression}: shows how to specify the expression matrix 
    \item \textbf{test\_score}:  runs the naive and simple analysis we provide as a demonstration, using the specified geneset and patient (sample) ids, getting the 
expected result.   The scoring method we use does a t-test comparing gene expression for the specified patients, in the specified geneset (here, "YAMANAKA\_GLIOBLASTOMA\_SURVIVAL\_UP")
against an equal number of randomly selected genes.  The t-test is repeated for each of the patients. 

\end{itemize}

\section{Please Return a Rich and Detailed Result}

Please return a rich and detailed result from your analysis:  it will be packaged up in JSON, and returned via a websocket to the 
user's web browser, where we will display it for the user to explore.   

For example, here is a brief session with AnalysisDemo (taken from the unitTests).  Once the result is calculated and returned,
we print it out to the console to demonstrate the level of detail we ask you to return.

\begin{verbatim}
data("msigdb")                     # variable "genesets" is loaded
data("tbl.mrnaUnified.TCGA.GBM")   # variabole "tbl.mrna" is loaded

   # tcga gbm samples with survival >6 years post diagnsosis, by inspection in Oncoscape
longSurvivors <- list("TCGA.02.0014", "TCGA.02.0021", "TCGA.02.0028", "TCGA.02.0080", "TCGA.02.0114",
                      "TCGA.06.6693", "TCGA.08.0344", "TCGA.12.0656", "TCGA.12.0818", "TCGA.12.1088")

geneset.of.interest <- genesets["YAMANAKA_GLIOBLASTOMA_SURVIVAL_UP"]
demo <- AnalysisDemo(sampleIDs=longSurvivors, 
                     geneSet=geneset.of.interest,
                     sampleDescription="TCGA GBM long survivors",
                     geneSetDescription="msgidb:YAMANAKA_GLIOBLASTOMA_SURVIVAL_UP")
   
demo <- setExpressionData(demo, tbl.mrna)

set.seed(123)
scores <- score(demo)
   found 8/10 overlapping samples in the expession data, 8/11 overlapping genes

scores

  $sample.title
  [1] "TCGA GBM long survivors"
  
  $geneSet.title
  [1] "msgidb:YAMANAKA_GLIOBLASTOMA_SURVIVAL_UP"
  
  $actual.samples.used
  [1] "TCGA.02.0014" "TCGA.02.0021" "TCGA.02.0028" "TCGA.02.0080" "TCGA.02.0114" 
  [6] "TCGA.08.0344" "TCGA.12.0656" "TCGA.12.1088"
  
  $actual.genes.used
  [1] "PKM2"   "RAB32"  "SLN"    "LDHC"   "SLC2A3" "ITGA5"  "DYRK3"  "TPI1"  
  
  $unmatched.samples
  [1] "TCGA.06.6693" "TCGA.12.0818"
  
  $unmatched.genes
  [1] "FGFBP2"  "STK40"   "EMILIN2"
  
  $pvals
  $pvals$TCGA.02.0014
  [1] 0.01191561
  
  $pvals$TCGA.02.0021
  [1] 0.8945468
  
  $pvals$TCGA.02.0028
  [1] 0.8122718
  
  $pvals$TCGA.02.0080
  [1] 0.01048628
  
  $pvals$TCGA.02.0114
  [1] 0.02630814
  
  $pvals$TCGA.08.0344
  [1] 0.2464011
  
  $pvals$TCGA.12.0656
  [1] 0.3623026
  
  $pvals$TCGA.12.1088
  [1] 0.6808923



\end{verbatim}


\end{document}


